services:
  - type: web
    name: employee-database-backend
    env: node
    root: server  # Add this line to point to the server directory
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: employeemongodb
          property: connectionString

databases:
  - name: employeemongodb
    databaseName: employees
    user: employeeuser